### PR TITLE
Expose type hints

### PR DESCRIPTION
**Pull request by cburgdorf**
WIP

### CODE REVIEW

**Comment by cburgdorf** [comment]
@pipermerriam Looks interesting! I haven't looked into how to best add types to this library. I just did the minimal work to expose *some* type information so that we can get stronger type guarantees in Py-EVM/Trinity. Here's a WIP PR to that: https://github.com/ethereum/py-evm/pull/1948

Currently any function like:

```python
def do_something(self, BlockHeaderAPI)`
   ...
```

...can basically called with almost anything including `BlockAPI`, `ReceiptAPI`, `SignedTransactionAPI` etc.

This has caused a bug with Trinity beam sync: https://github.com/ethereum/trinity/pull/1830

**Comment by cburgdorf** [comment]
>Which is probably overdue for this library

Yes, I don't think there's away around it. 

>but also potentially complicated with how broadly this library is used.

Why do you think so? It's currently on version `1.2.0`, if we release a version `2.0.0` nobody who takes semver serious should be affected by it, no? No project that uses py-rlp and follows semver would automatically upgrade to `2.0.0`. Instead, it takes a deliberate decision from someone (someone who cares about typing) to manually upgrade to this new version.

Or am I missing something important?

**Comment by pipermerriam** [comment]
> Or am I missing something important?

No, just that when we have dependency chains like where multiple libraries in the chain all depend on `pyrlp` then we have often ended up with broken upgrades because one path of the dependency chain still requires `>=1.x,<2` and another now requires `>=2.x,<3`.

I'm only pointing it out so that we're careful.  I think you are correct that we can safely do a major version bump.

**If** we plan to do a major bump, we would likely do ourselves a favor to examine whether there is anything else in the API we want to break/improve.

**Comment by cburgdorf** [comment]
I'm going to close this as I've found a shortcut in Py-EVM to get most of the benefits without depending on a new py-rlp release: https://github.com/ethereum/py-evm/pull/1948

I'm also not sure if it's worth making a bigger py-rlp refactoring or if it would be better to simply create nice typed bindings to a well maintained and fast rust rlp library. That way we would also get a nice speedup.

**Pull request closed without merging**
