### PR TITLE
Library cleanup: Drop un-used APIs, optimizations, cleanup

### PR DESCRIPTION
**Pull request by pipermerriam**
### What was wrong

Low hanging fruit that was asking to be cleaned up.

### How was it fixed.

- Some simple optimizations like setting module level constants.
- Use of `to_tuple` and `to_list` in favor of accumulation pattern.
- Removal of multiple APIs that are not used and not tested. `pop`, `insert`, `append`, `descend`, `compare_length`
- More conversions to only accept `bytes` types instead of `str`

### CODE REVIEW

**Comment by pipermerriam** [comment]
Benchmark results:

#### This branch

```
Block serializations / sec: 1796.75
Block deserializations / sec: 760.56
TX serializations / sec: 24384.23
TX deserializations / sec: 13490.67
```

**Comment by gsalgado** [comment]
No noticeable performance improvement when importing a single block, unfortunately. Either with/without those changes we're spending around ~1.8s on 31k calls to `decode()` and ~2.5s on 17k calls to `encode()`. I'm going to find out what types we're serializing the most, because if they're not mutable we should be able to cache them easily

**Comment by gsalgado** [comment]
Yeah, I was wondering if we'd see performance improvements by using something like `p2p.ImmutableBlockHeader` for transactions, but it doesn't seem to. Indeed most of the rlp calls are to do with encoding/decoding of trie nodes, which are, as you pointed out bytes or lists of bytes

**Comment by pipermerriam** [comment]
I've been thinking about trying to switch the encoding and decoding processes to use `io.BytesIO` streams to cut down on the number of object copies that happen when encoding/decoding by directly reading or writing to the by stream.  I think I'll switch gears from https://github.com/ethereum/pyrlp/pull/62 to experimenting with that unless you want to take it on. (as well as looking into using some version of the [`fast_rlp.py`](https://github.com/ethereum/pyethereum/blob/develop/ethereum/fast_rlp.py) from pyethereum in our trie.

**Comment by gsalgado** [comment]
@pipermerriam go for it! I'm trying to get the full-sync code into acceptable shape to be merged so that others can try it and run the performance benchmarks as well

**Pull request merged**
