### PR TITLE
faster int-to-byte conversion

### PR DESCRIPTION
**Pull request by pipermerriam**
A faster way to convert an integer to a single byte.

### CODE REVIEW

**Comment by pipermerriam** [comment]
46035b2bce632dd23f9aaee4cdcbe0a3c91850b1 is almost 25% faster than b910fb2

```
struct.pack
took 0.029844999313354492 s to run 100000 times. 0.2984499931335449 us per run
chr(v).encode("latin1")
took 0.03609776496887207 s to run 100000 times. 0.3609776496887207 us per run
bytes([v])
took 0.02938699722290039 s to run 100000 times. 0.2938699722290039 us per run
lookup ALL_BYTES.get(n)
took 0.024296998977661133 s to run 100000 times. 0.24296998977661133 us per run
lookup ALL_BYTES.__getitem__(n)
took 0.020754098892211914 s to run 100000 times. 0.20754098892211914 us per run
lookup: ALL_BYTES[n]
took 0.015943288803100586 s to run 100000 times. 0.15943288803100586 us per run
lookup: lambda n: ALL_BYTES[n]
took 0.0262298583984375 s to run 100000 times. 0.262298583984375 us per run
```

**Comment by davesque** [comment]
Would it be still faster to index into a list instead of keying into a dict?

**Comment by carver** [comment]
It's way too fun to get sucked into this stuff. I was a little surprised that dict was faster:

```
ALL_BYTES_DICT = { i: struct.pack('B', i) for i in range(256) }
ALL_BYTES_LIST = [struct.pack('B', i) for i in range(256)]

In [175]: profile(lambda run: ALL_BYTES_DICT[run % 256], runs=10000000)
took 1.4319722652435303 s to run 10000000 times. 0.14319722652435302 us per run

In [176]: profile(lambda run: ALL_BYTES_LIST[run % 256], runs=10000000)
took 1.5210247039794922 s to run 10000000 times. 0.15210247039794922 us per run
```

**Comment by davesque** [comment]
Wow that's shocking. I'm going to have to poke around and figure out why that is.

**Comment by carver** [comment]
But tuple wins: 

```
In [177]: ALL_BYTES_TUPLE = tuple(struct.pack('B', i) for i in range(256))

In [179]: profile(lambda run: ALL_BYTES_TUPLE[run % 256], runs=10000000)
took 1.369187355041504 s to run 10000000 times. 0.1369187355041504 us per run
```

**Comment by davesque** [comment]
Pretty mysterious.  The C implementation for the `__getitem__` method on list and tuple objects is basically the same and just indexes into a contiguously allocated list as I expected.  However, the implementation for `dict.__getitem__` does a fair bit more and even calls out to a subroutine to fetch the values from the hash table.  So it has to make a stack frame and all that.  I'm stumped on that one.  Don't know why it would be as fast as a list.

**Comment by pipermerriam** [comment]
https://github.com/ethereum/pyrlp/pull/65

**Pull request merged**
