### PR TITLE
Segmentation fault anyone?

### PR DESCRIPTION
**Pull request by cburgdorf**

### CODE REVIEW

**Comment by cburgdorf** [comment]
@carver @pipermerriam 

The changes in this PR are necessary to have CI still build this project. But notice the segmentation fault in the pypy builds. I'm wondering what your thoughts are about dropping pypy support. It would cost some extra effort to produce pypy builds for the new rust backend and so I was considering to simply keep Python fallbacks of `encode_raw` / `decode_raw` for pypy around but now that I noticed it doesn't even build anymore without these changes I'm wondering what your thoughts are on dropping pypy support altogether?

**Comment by pipermerriam** [comment]
It would be nice to know whether or not anyone is actually using pypy.  My guess is if we have **any** pypy users, there are very few.  I'm +0 on dropping support.

**Comment by carver** [comment]
Yeah, it makes me sad because there are some meaningful speedups. But they've fallen pretty far behind the versions of python that we want to use anyway, so :ok_hand: to drop. (With a major version bump)

**Comment by cburgdorf** [comment]
Alright, thank you for your input. I'll update #125 and will continue the discussion from there.

**Pull request closed without merging**
