### PR TITLE
Cache the RLP of nested items when decoding

### PR DESCRIPTION
**Pull request by gsalgado**
Closes: #93

### CODE REVIEW

**Comment by gsalgado** [comment]
This basically changes `consume_item()` to return the RLP of each item alongside the items themselves, and then in `decode()` we split them so that we can pass just the items to `sedes.deserialize()` and use the RLP to populate the cache after the deserialization. I also had to change `consume_length_prefix()` to return the consumed prefix so that we can recreate the RLP of each item

**Comment by gsalgado** [comment]
Deserialization performance is a lot worse with those changes, though. :-(

```
(pyrlp) salgado@delgadito~/src/pyrlp (master) $ python tests/speed.py
Block serializations / sec: 1415.42
Block deserializations / sec: 1149.07
TX serializations / sec: 19006.88
TX deserializations / sec: 15425.95
```

```
(pyrlp) salgado@delgadito~/src/pyrlp (issue-93) $ python tests/speed.py
Block serializations / sec: 1433.39
Block deserializations / sec: 519.21
TX serializations / sec: 18506.39
TX deserializations / sec: 6903.52
```

Although the performance gains from having proper caching may outweigh the overhead when deserializing, it'd be good if we could reduce that overhead. Will have to investigate

**Comment by gsalgado** [comment]
Significant improvements with the last commit, but still some overhead. I guess the only way to avoid the overhead completely would be to pass the broken down rlp to `sedes.deserialize()` so that both the deserialization and caching are done in a single pass. As long as we do one pass to deserialize and another to apply the cache, there will be some overhead, obviously.

```
(pyrlp) salgado@delgadito~/src/pyrlp (issue-93) $ python tests/speed.py
Block serializations / sec: 1430.24
Block deserializations / sec: 837.46
TX serializations / sec: 17738.90
TX deserializations / sec: 11199.64
```

**Comment by gsalgado** [comment]
@pipermerriam how do you feel about this?

**Comment by gsalgado** [comment]
I completely agree that those functions are already hard to read and this change is making that even worse, but this is not really an optimization -- it's fixing the caching which in its current state is pretty much useless as most of the time we're dealing with lists of items and not individual items. Also, the less invasive approaches I tried (partly to avoid adding yet more complexity to those existing functions) incurred significant overhead in a performance-critical code path. As for the performance gains it's hard to measure because this will have an effect on many things other than `make_trie_root_and_nodes()` (which is what initially caused me to find this bug).

**Comment by pipermerriam** [comment]
Available in `v1.0.2`

**Pull request merged**
